import numpy as np
import pandas as pd
import tifffile
from pathlib import Path

from PIL import Image
import matplotlib.pyplot as plt
from matplotlib.colors import hsv_to_rgb


# ============================================================
# USER SETTINGS
# ============================================================

# ------------------------------------------------------------
# CHANNEL-SPECIFIC INPUTS
# ------------------------------------------------------------
#
# Each channel should have:
#
#   1. The CellProfiler object-label TIFF
#   2. The CellProfiler object CSV for that channel
#
# The organoid mask CSV is shared because it describes the
# corresponding organoid mask.
# ------------------------------------------------------------

tiff_path = Path(
    "/home/oltij/Desktop/LHX6Aligned/CellMask.tiff"
)

channel_csv_path = Path(
    "/home/oltij/Desktop/LHX6Aligned/MyExpt_FilterObjects2.csv"
)

# ------------------------------------------------------------
# ORGANOID MASK CELLPROFILER CSV
# ------------------------------------------------------------
#
# This is the CSV containing the organoid mask object.
#
# Example:
#   /home/oltij/Desktop/PVImage/MyExpt_FilterObjects.csv
#
# The script uses AreaShape_Area from this file as the
# organoid mask area.
# ------------------------------------------------------------

organoid_csv_path = Path(
    "/home/oltij/Desktop/LHX6Aligned/MyExpt_FilterObjects.csv"
)

# Name of this channel for the summary statistics
CHANNEL_NAME = "LHX6"

# Floating-point tolerance for CellProfiler centroid comparison
CENTER_TOLERANCE = 1e-6


# ============================================================
# OUTPUT DIRECTORY
# ============================================================

# Everything generated by this script goes into one directory.

output_dir = tiff_path.parent / "ROI_analysis"

output_dir.mkdir(
    parents=True,
    exist_ok=True
)

print("=" * 70)
print("OUTPUT DIRECTORY")
print("=" * 70)
print(output_dir)


# ============================================================
# LOAD TIFF
# ============================================================

print("\n" + "=" * 70)
print("LOADING TIFF")
print("=" * 70)

image = tifffile.imread(tiff_path)

print(f"Image shape: {image.shape}")
print(f"Image dtype: {image.dtype}")
print(f"Minimum value: {image.min()}")
print(f"Maximum value: {image.max()}")

if image.ndim != 2:
    raise ValueError(
        f"Expected a 2D grayscale TIFF, but got shape {image.shape}"
    )


# ============================================================
# FIND UNIQUE INTENSITY LEVELS
# ============================================================

unique_values = np.unique(image)

if 0 not in unique_values:
    raise ValueError(
        "No zero-valued background was found in the TIFF."
    )

nonzero_values = unique_values[
    unique_values != 0
]

n_objects = len(nonzero_values)

print(f"\nUnique intensity values: {len(unique_values):,}")
print(f"Non-background intensity levels: {n_objects:,}")


# ============================================================
# CHECK INTENSITY SPACING
# ============================================================

print("\n" + "=" * 70)
print("CHECKING INTENSITY LEVEL SPACING")
print("=" * 70)

if n_objects > 1:

    differences = np.diff(nonzero_values)

    print(f"Minimum spacing: {differences.min()}")
    print(f"Maximum spacing: {differences.max()}")
    print(f"Mean spacing:    {differences.mean():.3f}")

    if differences.max() - differences.min() <= 2:

        print(
            "\nIntensity levels are evenly spaced."
        )

        print(
            "This is consistent with a CellProfiler object-label "
            "image that has been rescaled to 16-bit."
        )

    else:

        print(
            "\nWARNING: intensity levels are not perfectly evenly spaced."
        )

        print(
            "The script will use the actual unique levels rather "
            "than assuming a mathematical scaling formula."
        )


# ============================================================
# RECONSTRUCT OBJECT LABELS
# ============================================================

print("\n" + "=" * 70)
print("RECONSTRUCTING ROI LABELS")
print("=" * 70)

label_image = np.zeros(
    image.shape,
    dtype=np.uint16
)

for roi_id, intensity in enumerate(
    nonzero_values,
    start=1
):

    label_image[
        image == intensity
    ] = roi_id


# ============================================================
# VERIFY RECONSTRUCTED LABELS
# ============================================================

reconstructed_ids = np.unique(
    label_image
)

expected_ids = np.arange(
    0,
    n_objects + 1
)

if np.array_equal(
    reconstructed_ids,
    expected_ids
):

    print(
        f"Successfully reconstructed {n_objects:,} ROIs."
    )

else:

    print(
        "WARNING: reconstructed ROI labels are unexpected."
    )


# ============================================================
# SAVE RECONSTRUCTED LABEL TIFF
# ============================================================

reconstructed_path = (
    output_dir /
    f"{CHANNEL_NAME}_reconstructed_labels.tiff"
)

tifffile.imwrite(
    reconstructed_path,
    label_image
)

print(
    "\nReconstructed label TIFF saved to:"
)

print(reconstructed_path)


# ============================================================
# MEASURE RECONSTRUCTED ROIs
# ============================================================

print("\n" + "=" * 70)
print("MEASURING RECONSTRUCTED ROIs")
print("=" * 70)

summary_records = []

for roi_id in range(
    1,
    n_objects + 1
):

    y, x = np.where(
        label_image == roi_id
    )

    if len(x) == 0:
        continue

    summary_records.append(
        {
            "ROI": roi_id,

            "OriginalIntensity":
                int(nonzero_values[roi_id - 1]),

            "TIFF_PixelCount":
                len(x),

            "TIFF_MinX":
                int(x.min()),

            "TIFF_MaxX_ActualPixel":
                int(x.max()),

            "TIFF_MinY":
                int(y.min()),

            "TIFF_MaxY_ActualPixel":
                int(y.max()),

            "TIFF_CenterX":
                float(x.mean()),

            "TIFF_CenterY":
                float(y.mean()),
        }
    )


tiff_df = pd.DataFrame(
    summary_records
)


# ============================================================
# LOAD CHANNEL CELLPROFILER CSV
# ============================================================

print("\n" + "=" * 70)
print(f"LOADING {CHANNEL_NAME} CELLPROFILER CSV")
print("=" * 70)

cp = pd.read_csv(
    channel_csv_path
)

print(
    f"CellProfiler rows: {len(cp):,}"
)

print(
    f"CellProfiler columns: {len(cp.columns):,}"
)


# ============================================================
# CHECK REQUIRED CHANNEL COLUMNS
# ============================================================

required_columns = [
    "ImageNumber",
    "ObjectNumber",
    "AreaShape_Area",
    "AreaShape_BoundingBoxMaximum_X",
    "AreaShape_BoundingBoxMaximum_Y",
    "AreaShape_BoundingBoxMinimum_X",
    "AreaShape_BoundingBoxMinimum_Y",
    "AreaShape_Center_X",
    "AreaShape_Center_Y",
]

missing = [
    col
    for col in required_columns
    if col not in cp.columns
]

if missing:

    raise ValueError(
        "Missing required CellProfiler columns:\n"
        + "\n".join(missing)
    )


# ============================================================
# CHECK IMAGE NUMBERS
# ============================================================

print("\nCellProfiler ImageNumbers:")

print(
    cp["ImageNumber"]
    .value_counts()
    .sort_index()
)


# ============================================================
# SELECT IMAGE 1
# ============================================================

if cp["ImageNumber"].nunique() == 1:

    cp_image = cp.copy()

else:

    print(
        "\nWARNING: CSV contains multiple ImageNumbers."
    )

    print(
        "Using ImageNumber = 1 for this TIFF."
    )

    cp_image = cp[
        cp["ImageNumber"] == 1
    ].copy()


print(
    f"\nCellProfiler objects for this image: "
    f"{len(cp_image):,}"
)


# ============================================================
# PREPARE CELLPROFILER DATA
# ============================================================

cp_compare = cp_image[
    [
        "ObjectNumber",
        "AreaShape_Area",
        "AreaShape_BoundingBoxMaximum_X",
        "AreaShape_BoundingBoxMaximum_Y",
        "AreaShape_BoundingBoxMinimum_X",
        "AreaShape_BoundingBoxMinimum_Y",
        "AreaShape_Center_X",
        "AreaShape_Center_Y",
    ]
].copy()


cp_compare = cp_compare.rename(
    columns={
        "ObjectNumber":
            "ROI",

        "AreaShape_Area":
            "CP_Area",

        "AreaShape_BoundingBoxMaximum_X":
            "CP_MaxX_Exclusive",

        "AreaShape_BoundingBoxMaximum_Y":
            "CP_MaxY_Exclusive",

        "AreaShape_BoundingBoxMinimum_X":
            "CP_MinX",

        "AreaShape_BoundingBoxMinimum_Y":
            "CP_MinY",

        "AreaShape_Center_X":
            "CP_CenterX",

        "AreaShape_Center_Y":
            "CP_CenterY",
    }
)


# ============================================================
# MERGE TIFF AND CELLPROFILER RESULTS
# ============================================================

verification = pd.merge(
    cp_compare,
    tiff_df,
    on="ROI",
    how="outer",
    indicator=True
)


# ============================================================
# ROI EXISTENCE STATUS
# ============================================================

verification["ROI_Status"] = "MATCH"

verification.loc[
    verification["_merge"] == "left_only",
    "ROI_Status"
] = "CP_ONLY"

verification.loc[
    verification["_merge"] == "right_only",
    "ROI_Status"
] = "TIFF_ONLY"


# ============================================================
# AREA VERIFICATION
# ============================================================

verification["Area_Difference"] = (
    verification["TIFF_PixelCount"]
    - verification["CP_Area"]
)

verification["Area_Match"] = (
    verification["Area_Difference"] == 0
)


# ============================================================
# BOUNDING BOX VERIFICATION
# ============================================================

verification["MinX_Difference"] = (
    verification["TIFF_MinX"]
    - verification["CP_MinX"]
)

verification["MaxX_Difference"] = (
    verification["TIFF_MaxX_ActualPixel"]
    - verification["CP_MaxX_Exclusive"]
)

verification["MinY_Difference"] = (
    verification["TIFF_MinY"]
    - verification["CP_MinY"]
)

verification["MaxY_Difference"] = (
    verification["TIFF_MaxY_ActualPixel"]
    - verification["CP_MaxY_Exclusive"]
)

verification["BoundingBox_Match"] = (
    (verification["MinX_Difference"] == 0)
    &
    (verification["MaxX_Difference"] == -1)
    &
    (verification["MinY_Difference"] == 0)
    &
    (verification["MaxY_Difference"] == -1)
)


# ============================================================
# CENTER VERIFICATION
# ============================================================

verification["CenterX_Difference"] = (
    verification["TIFF_CenterX"]
    - verification["CP_CenterX"]
)

verification["CenterY_Difference"] = (
    verification["TIFF_CenterY"]
    - verification["CP_CenterY"]
)

verification["Center_Match"] = (
    np.isclose(
        verification["CenterX_Difference"],
        0,
        atol=CENTER_TOLERANCE
    )
    &
    np.isclose(
        verification["CenterY_Difference"],
        0,
        atol=CENTER_TOLERANCE
    )
)


# ============================================================
# FULL VERIFICATION
# ============================================================

verification["FULL_MATCH"] = (
    (verification["ROI_Status"] == "MATCH")
    &
    verification["Area_Match"]
    &
    verification["BoundingBox_Match"]
    &
    verification["Center_Match"]
)


# ============================================================
# SAVE VERIFICATION CSV
# ============================================================

verification_path = (
    output_dir /
    f"{CHANNEL_NAME}_ROI_verification.csv"
)

verification.to_csv(
    verification_path,
    index=False
)


# ============================================================
# VERIFICATION SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("VERIFICATION RESULTS")
print("=" * 70)

cp_count = len(cp_compare)
tiff_count = len(tiff_df)

print(
    f"\nCellProfiler ROIs:       {cp_count:,}"
)

print(
    f"TIFF reconstructed ROIs: {tiff_count:,}"
)


cp_only = (
    verification["ROI_Status"]
    == "CP_ONLY"
).sum()

tiff_only = (
    verification["ROI_Status"]
    == "TIFF_ONLY"
).sum()

matched = (
    verification["ROI_Status"]
    == "MATCH"
).sum()

print(
    f"\nROIs present in both:       {matched:,}"
)

print(
    f"ROIs only in CellProfiler:  {cp_only:,}"
)

print(
    f"ROIs only in TIFF:          {tiff_only:,}"
)


matched_rows = verification[
    verification["ROI_Status"] == "MATCH"
]

area_matches = (
    matched_rows["Area_Match"]
    .sum()
)

bbox_matches = (
    matched_rows["BoundingBox_Match"]
    .sum()
)

center_matches = (
    matched_rows["Center_Match"]
    .sum()
)

full_matches = (
    matched_rows["FULL_MATCH"]
    .sum()
)

print(
    f"\nArea matches:          "
    f"{area_matches:,} / {len(matched_rows):,}"
)

print(
    f"Bounding-box matches: "
    f"{bbox_matches:,} / {len(matched_rows):,}"
)

print(
    f"Center matches:       "
    f"{center_matches:,} / {len(matched_rows):,}"
)

print(
    f"FULL matches:         "
    f"{full_matches:,} / {len(matched_rows):,}"
)


# ============================================================
# CHECK ROI NUMBERING
# ============================================================

print("\n" + "=" * 70)
print("CHECKING ROI NUMBERING")
print("=" * 70)

cp_ids = set(
    cp_compare["ROI"]
    .dropna()
    .astype(int)
)

tiff_ids = set(
    tiff_df["ROI"]
    .dropna()
    .astype(int)
)

if cp_ids == tiff_ids:

    print(
        "\nROI numbering is IDENTICAL between "
        "CellProfiler and the reconstructed TIFF."
    )

else:

    print(
        "\nWARNING: ROI numbering differs."
    )

    print(
        "CellProfiler-only IDs:",
        sorted(cp_ids - tiff_ids)[:20]
    )

    print(
        "TIFF-only IDs:",
        sorted(tiff_ids - cp_ids)[:20]
    )


# ============================================================
# SHOW PROBLEMATIC ROIs
# ============================================================

problems = verification[
    ~verification["FULL_MATCH"]
]

if len(problems) > 0:

    print("\n" + "=" * 70)
    print("ROIs THAT DID NOT FULLY MATCH")
    print("=" * 70)

    display_columns = [
        "ROI",
        "ROI_Status",
        "CP_Area",
        "TIFF_PixelCount",
        "Area_Difference",
        "CP_MinX",
        "TIFF_MinX",
        "CP_MaxX_Exclusive",
        "TIFF_MaxX_ActualPixel",
        "CP_MinY",
        "TIFF_MinY",
        "CP_MaxY_Exclusive",
        "TIFF_MaxY_ActualPixel",
        "CP_CenterX",
        "TIFF_CenterX",
        "CP_CenterY",
        "TIFF_CenterY",
    ]

    print(
        problems[display_columns]
        .head(30)
        .to_string(index=False)
    )

else:

    print(
        "\nALL ROIs MATCH PERFECTLY."
    )


# ============================================================
# SAVE PIXEL COORDINATES
# ============================================================

print("\n" + "=" * 70)
print("EXTRACTING PIXEL COORDINATES")
print("=" * 70)

pixels_path = (
    output_dir /
    f"{CHANNEL_NAME}_ROI_pixels.csv"
)

roi_values = label_image.ravel()

pixel_indices = np.flatnonzero(
    roi_values != 0
)

roi_ids = roi_values[
    pixel_indices
]

height, width = label_image.shape

ys = pixel_indices // width
xs = pixel_indices % width

pixels_df = pd.DataFrame(
    {
        "ROI": roi_ids.astype(np.uint16),
        "X": xs.astype(np.int32),
        "Y": ys.astype(np.int32),
    }
)

pixels_df.to_csv(
    pixels_path,
    index=False
)

print(
    f"Saved {len(pixels_df):,} object pixels."
)

print(
    pixels_path
)


# ============================================================
# LOAD ORGANOID MASK CELLPROFILER CSV
# ============================================================

print("\n" + "=" * 70)
print("LOADING ORGANOID MASK CSV")
print("=" * 70)

organoid = pd.read_csv(
    organoid_csv_path
)

print(
    f"Organoid CSV rows: {len(organoid):,}"
)

print(
    f"Organoid CSV columns: {len(organoid.columns):,}"
)


# ============================================================
# CHECK ORGANOID REQUIRED COLUMNS
# ============================================================

organoid_required = [
    "ImageNumber",
    "ObjectNumber",
    "FileName_DNA",
    "AreaShape_Area",
    "AreaShape_BoundingBoxArea",
    "AreaShape_BoundingBoxMaximum_X",
    "AreaShape_BoundingBoxMaximum_Y",
    "AreaShape_BoundingBoxMinimum_X",
    "AreaShape_BoundingBoxMinimum_Y",
    "AreaShape_Center_X",
    "AreaShape_Center_Y",
]

missing_organoid = [
    col
    for col in organoid_required
    if col not in organoid.columns
]

if missing_organoid:

    raise ValueError(
        "Missing required organoid-mask columns:\n"
        + "\n".join(missing_organoid)
    )


# ============================================================
# SELECT CORRESPONDING ORGANOID
# ============================================================
#
# For this script, the TIFF is being treated as the image
# corresponding to ImageNumber = 1.
#
# If the organoid CSV has only one row, that row is used.
# If it has multiple rows, ImageNumber = 1 is used.
# ============================================================

if len(organoid) == 1:

    organoid_image = organoid.copy()

else:

    organoid_image = organoid[
        organoid["ImageNumber"] == 1
    ].copy()


if len(organoid_image) == 0:

    raise ValueError(
        "No organoid-mask object was found for ImageNumber = 1."
    )


if len(organoid_image) > 1:

    print(
        "\nWARNING: More than one organoid object was found "
        "for this image."
    )

    print(
        "All organoid objects will be retained in the "
        "summary statistics."
    )


# ============================================================
# CREATE ORGANOID SUMMARY
# ============================================================

organoid_summary = organoid_image[
    organoid_required
].copy()


# ============================================================
# CALCULATE ROI COUNTS AND DENSITY
# ============================================================

roi_count = int(n_objects)


# ------------------------------------------------------------
# If there is one organoid object, this is straightforward.
#
# If there are multiple organoid objects, the ROI density is
# calculated against the total organoid area.
# ------------------------------------------------------------

total_organoid_area = (
    organoid_summary["AreaShape_Area"]
    .sum()
)


roi_density_per_pixel = (
    roi_count /
    total_organoid_area
)


roi_density_per_100k_pixels = (
    roi_density_per_pixel *
    100000
)


roi_density_per_1m_pixels = (
    roi_density_per_pixel *
    1000000
)


# ============================================================
# ADD SUMMARY STATISTICS
# ============================================================

organoid_summary[
    "Channel"
] = CHANNEL_NAME

organoid_summary[
    "ROI_Count"
] = roi_count

organoid_summary[
    "Total_Organoid_Mask_Area_Pixels"
] = total_organoid_area

organoid_summary[
    "ROI_Density_per_Pixel"
] = roi_density_per_pixel

organoid_summary[
    "ROI_Density_per_100000_Pixels"
] = roi_density_per_100k_pixels

organoid_summary[
    "ROI_Density_per_1000000_Pixels"
] = roi_density_per_1m_pixels


# ============================================================
# ADD TIFF INFORMATION
# ============================================================

organoid_summary[
    "TIFF_ROI_Count"
] = tiff_count

organoid_summary[
    "TIFF_File"
] = tiff_path.name

organoid_summary[
    "Channel_CellProfiler_CSV"
] = channel_csv_path.name

organoid_summary[
    "Organoid_CellProfiler_CSV"
] = organoid_csv_path.name


# ============================================================
# SAVE SUMMARY STATISTICS
# ============================================================

summary_statistics_path = (
    output_dir /
    f"{CHANNEL_NAME}_summary_statistics.csv"
)

organoid_summary.to_csv(
    summary_statistics_path,
    index=False
)


# ============================================================
# PRINT SUMMARY STATISTICS
# ============================================================

print("\n" + "=" * 70)
print(f"{CHANNEL_NAME} SUMMARY STATISTICS")
print("=" * 70)

print(
    f"\nChannel:                 {CHANNEL_NAME}"
)

print(
    f"ROI count:               {roi_count:,}"
)

print(
    f"Organoid mask area:      "
    f"{total_organoid_area:,.0f} pixels"
)

print(
    f"ROI density / pixel:     "
    f"{roi_density_per_pixel:.10f}"
)

print(
    f"ROI density / 100,000:   "
    f"{roi_density_per_100k_pixels:.4f}"
)

print(
    f"ROI density / 1,000,000: "
    f"{roi_density_per_1m_pixels:.4f}"
)

print(
    "\nSummary statistics saved to:"
)

print(
    summary_statistics_path
)


# ============================================================
# CREATE COLOR-CODED ROI IMAGE
# ============================================================

print("\n" + "=" * 70)
print("CREATING VISUAL VERIFICATION IMAGES")
print("=" * 70)

print("\nCreating color-coded ROI image...")

hsv = np.zeros(
    (n_objects + 1, 3),
    dtype=np.float32
)

hsv[:, 0] = (
    np.arange(n_objects + 1)
    / max(n_objects, 1)
)

hsv[:, 1] = 1.0
hsv[:, 2] = 1.0

rgb_colors = (
    hsv_to_rgb(hsv) * 255
).astype(np.uint8)

rgb_colors[0] = [0, 0, 0]

color_image = rgb_colors[
    label_image
]

color_path = (
    output_dir /
    f"{CHANNEL_NAME}_reconstructed_labels_color.tiff"
)

Image.fromarray(
    color_image,
    mode="RGB"
).save(color_path)

print(
    "Color-coded ROI image:"
)

print(color_path)


# ============================================================
# CREATE ROI BOUNDARY OVERLAY
# ============================================================

print("\nCreating verification overlay...")

labels = label_image

boundary = np.zeros(
    labels.shape,
    dtype=bool
)

boundary[1:, :] |= (
    labels[1:, :] != labels[:-1, :]
)

boundary[:-1, :] |= (
    labels[:-1, :] != labels[1:, :]
)

boundary[:, 1:] |= (
    labels[:, 1:] != labels[:, :-1]
)

boundary[:, :-1] |= (
    labels[:, :-1] != labels[:, 1:]
)

boundary &= (
    labels != 0
)


# Use original image as grayscale background

if image.max() > 0:

    normalized = (
        image.astype(np.float32)
        / image.max()
        * 255
    ).astype(np.uint8)

else:

    normalized = np.zeros_like(
        image,
        dtype=np.uint8
    )


overlay = np.stack(
    [
        normalized,
        normalized,
        normalized
    ],
    axis=-1
)


# Red ROI boundaries

overlay[boundary] = [
    255,
    0,
    0
]


overlay_path = (
    output_dir /
    f"{CHANNEL_NAME}_verification_overlay.tiff"
)

Image.fromarray(
    overlay,
    mode="RGB"
).save(overlay_path)

print(
    "Verification overlay:"
)

print(overlay_path)


# ============================================================
# SIDE-BY-SIDE VISUAL COMPARISON
# ============================================================

print("\nCreating side-by-side comparison...")

fig, axes = plt.subplots(
    1,
    2,
    figsize=(16, 8)
)

axes[0].imshow(
    image,
    cmap="gray"
)

axes[0].set_title(
    f"Original {CHANNEL_NAME} CellMask TIFF"
)

axes[0].axis("off")


axes[1].imshow(
    color_image
)

axes[1].set_title(
    f"Reconstructed {CHANNEL_NAME} ROIs"
)

axes[1].axis("off")

plt.tight_layout()

comparison_path = (
    output_dir /
    f"{CHANNEL_NAME}_visual_verification.png"
)

plt.savefig(
    comparison_path,
    dpi=200,
    bbox_inches="tight"
)

plt.close()

print(
    "Side-by-side comparison:"
)

print(comparison_path)


# ============================================================
# FINAL OUTPUT
# ============================================================

print("\n" + "=" * 70)
print("DONE")
print("=" * 70)

print("\nCreated files:")

print(
    f"\n1. Reconstructed label TIFF:\n"
    f"   {reconstructed_path}"
)

print(
    f"\n2. ROI verification CSV:\n"
    f"   {verification_path}"
)

print(
    f"\n3. Pixel-coordinate CSV:\n"
    f"   {pixels_path}"
)

print(
    f"\n4. Color-coded ROI TIFF:\n"
    f"   {color_path}"
)

print(
    f"\n5. Boundary overlay TIFF:\n"
    f"   {overlay_path}"
)

print(
    f"\n6. Visual comparison PNG:\n"
    f"   {comparison_path}"
)

print(
    f"\n7. SUMMARY STATISTICS CSV:\n"
    f"   {summary_statistics_path}"
)

print("\n" + "=" * 70)
print("FINAL VERIFICATION")
print("=" * 70)

if (
    cp_count == tiff_count
    and cp_only == 0
    and tiff_only == 0
    and full_matches == matched
):

    print(
        "\nSUCCESS:"
    )

    print(
        "Every CellProfiler ROI has been recovered "
        "with matching area, bounding box, and centroid."
    )

else:

    print(
        "\nWARNING:"
    )

    print(
        "Some ROIs did not fully match."
    )

    print(
        "See the ROI verification CSV for details."
    )
